name: Proofreading Boutique
favicon: null
layout_spectrum: 0.6861286428757012
typography_spectrum: 0.8149198084138334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05798073927871883
  lightness: 0.4790453922469169
  saturation: 0.4121971901040524
  rhythmicContrast: 0.002302143955603242
purpose: []
